inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'perf/**/*'
    - 'spec/shared/lib/mrss/**/*'
    - 'test-apps/**/*'
    - 'vendor/**/*'

Style/Documentation:
  AllowedConstants: ['ClassMethods']
  Exclude:
    - 'gemfiles/**/*'
    - 'spec/**/*'

Style/DocumentationMethod:
  Exclude:
    - 'gemfiles/**/*'
    - 'spec/**/*'

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

# Mongoid behavior differs from ActiveRecord
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

# --------------------------------------------------
# These cops are having CI issues. Enable later.

Performance/StringInclude:
  Enabled: false

# --------------------------------------------------
# Cops below this line are intentionally disabled

Style/NumericPredicate:
  Enabled: false
