inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'perf/**/*'
    - 'test-apps/**/*'
    - 'vendor/**/*'

Style/Documentation:
  AllowedConstants: ['ClassMethods']
  Exclude:
    - 'gemfiles/**/*'
    - 'spec/**/*'

Style/DocumentationMethod:
  Exclude:
    - 'gemfiles/**/*'
    - 'spec/**/*'

# --------------------------------------------------
# These cops are having CI issues. Enable later.

Performance/StringInclude:
  Enabled: false

Performance/RegexpMatch:
  Exclude:
    - 'Gemfile'

# --------------------------------------------------
# Cops with specific files skipped. These can be inlined later.

Layout/LineContinuationLeadingSpace:
  Exclude:
    - 'spec/integration/app_spec.rb'

Lint/RedundantCopDisableDirective:
  Exclude:
    - 'spec/mongoid/version_spec.rb'

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/support/constraints.rb'

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - 'spec/mongoid/equality_spec.rb'

RSpec/AroundBlock:
  Exclude:
    - 'spec/support/constraints.rb'

RSpec/IdenticalEqualityAssertion:
  Exclude:
    - 'spec/mongoid/equality_spec.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/integration/callbacks_spec.rb'

Security/MarshalLoad:
  Exclude:
    - 'spec/mongoid/criteria/marshalable_spec.rb'

# --------------------------------------------------
# These cops are intentionally disabled due to incompatibility.

# Mongoid behavior differs from ActiveRecord
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

# --------------------------------------------------
# These cops are intentionally disabled due to style preference.

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# See: https://github.com/rubocop/rubocop/issues/11798
# Enforce multiline style if it becomes available in the future.
Style/WhileUntilModifier:
  Enabled: false
