---
name: Tests

'on':
  - push
  - pull_request

jobs:
  test:
    name: "${{matrix.ruby}}
      ${{matrix.gemfile || 'Gemfile'}}
      mongodb-${{matrix.mongodb || '6.0'}}
      ${{matrix.topology || 'server'}}
      ${{matrix.os || 'ubuntu-20.04'}}"
    env:
      CI: true
      TESTOPTS: '-v'
    runs-on: ${{matrix.os || 'ubuntu-20.04'}}
    continue-on-error: "${{matrix.experimental || false}}"
    strategy:
      fail-fast: false
      matrix:
        ruby: [ruby-2.7, ruby-3.0, ruby-3.1, ruby-3.2]
        # TODO: Use ubuntu-latest when supported.
        # See: https://github.com/mongodb-labs/drivers-evergreen-tools/issues/283
        os: ['ubuntu-20.04']
        topology: [server, replica_set] # TODO: sharded_cluster is broken
        include:
          # TODO: OS versions
          # - os: macos-latest
          #   ruby: ruby-3.2
          # - os: windows-latest
          #   ruby: ruby-3.2

          # Rails versions
          - ruby: ruby-3.2
            gemfile: gemfiles/rails-7.0.gemfile
            mongodb: '6.0'
            topology: replica_set
          - ruby: ruby-3.1
            gemfile: gemfiles/rails-6.1.gemfile
            mongodb: '5.0'
            topology: server
          - ruby: ruby-3.0
            gemfile: gemfiles/rails-6.1.gemfile
            mongodb: '4.4'
            topology: server
          - ruby: ruby-3.0
            gemfile: gemfiles/rails-6.0.gemfile
            mongodb: '4.4'
            topology: server
          - ruby: ruby-2.7
            gemfile: gemfiles/rails-6.0.gemfile
            mongodb: '4.4'
            topology: server

          # Driver versions
          # TODO: driver_master is broken
          # - ruby: ruby-3.2
          #   gemfile: gemfiles/driver_master.gemfile
          #   mongodb: '6.0'
          #   topology: replica_set
          - ruby: ruby-3.0
            gemfile: gemfiles/driver_stable.gemfile
            mongodb: '5.0'
            topology: replica_set
          - ruby: ruby-2.7
            gemfile: gemfiles/driver_min.gemfile
            mongodb: '4.4'
            topology: replica_set

          # BSON versions
          # TODO: bson_master is broken
          # - ruby: ruby-3.2
          #   gemfile: gemfiles/bson_master.gemfile
          #   mongodb: '6.0'
          #   topology: replica_set
          - ruby: ruby-2.7
            gemfile: gemfiles/bson_min.gemfile
            mongodb: '4.4'
            topology: replica_set

          # JRuby
          - ruby: jruby-9.4
            gemfile: gemfiles/rails-7.0.gemfile
            mongodb: '6.0'
            topology: replica_set
          - ruby: jruby-9.4
            gemfile: gemfiles/rails-6.0.gemfile
            mongodb: '5.0'
            topology: server

    steps:
    - name: repo checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - id: start-mongodb
      name: start mongodb
      uses: mongodb-labs/drivers-evergreen-tools@master
      with:
        version: "${{matrix.mongodb || '6.0'}}"
        topology: "${{matrix.topology || 'server'}}"
    - name: load ruby
      uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMFILE: "${{matrix.gemfile || 'Gemfile'}}"
      with:
        ruby-version: "${{matrix.ruby}}"
        bundler: 2
    - name: bundle
      run: bundle install --jobs 4 --retry 3
      env:
        BUNDLE_GEMFILE: "${{matrix.gemfile || 'Gemfile'}}"
    - name: test
      timeout-minutes: 60
      continue-on-error: "${{matrix.experimental || false}}"
      run: bundle exec rake spec
      env:
        BUNDLE_GEMFILE: "${{matrix.gemfile || 'Gemfile'}}"
        MONGODB_URI: "${{steps.start-mongodb.outputs.cluster-uri}}"
