---
name: Tests

'on':
  - push
  - pull_request

env:
  CI: true
  TESTOPTS: '-v'
  # TODO: https://github.com/mongodb-labs/drivers-evergreen-tools/issues/283
  CI_DEFAULT_OS: 'ubuntu-20.04'
  CI_DEFAULT_GEMFILE: 'Gemfile'
  CI_DEFAULT_MONGODB: '6.0'
  CI_DEFAULT_TOPOLOGY: 'server'

jobs:
  test:
    name: "${{matrix.ruby}}
      ${{matrix.gemfile || env.CI_DEFAULT_GEMFILE}}
      mongodb-${{matrix.mongodb || env.CI_DEFAULT_MONGODB}}
      ${{matrix.topology || env.CI_DEFAULT_TOPOLOGY}}
      ${{matrix.os || env.CI_DEFAULT_OS}}"
    runs-on: ${{matrix.os || env.CI_DEFAULT_OS}}
    continue-on-error: "${{matrix.experimental || false}}"
    strategy:
      fail-fast: false
      matrix:
        ruby: [ruby-2.7, ruby-3.0, ruby-3.1, ruby-3.2]
        os: [env.CI_DEFAULT_OS]
        topology: [server, replica_set, sharded_cluster]
        include:
          # TODO: OS versions
          # - os: macos-latest
          #   ruby: ruby-3.2
          # - os: windows-latest
          #   ruby: ruby-3.2

          # Rails versions
          - ruby: ruby-3.2
            gemfile: gemfiles/rails-7.0.gemfile
            mongodb: '6.0'
            topology: replica_set
          - ruby: ruby-3.1
            gemfile: gemfiles/rails-6.1.gemfile
            mongodb: '5.0'
            topology: server
          - ruby: ruby-3.0
            gemfile: gemfiles/rails-6.1.gemfile
            mongodb: '4.4'
            topology: server
          - ruby: ruby-3.0
            gemfile: gemfiles/rails-6.0.gemfile
            mongodb: '4.4'
            topology: server
          - ruby: ruby-2.7
            gemfile: gemfiles/rails-6.0.gemfile
            mongodb: '4.2'
            topology: server

          # Driver versions
          - ruby: ruby-3.2
            gemfile: gemfiles/driver_master.gemfile
            mongodb: '6.0'
            topology: replica_set
          - ruby: ruby-3.0
            gemfile: gemfiles/driver_stable.gemfile
            mongodb: '5.0'
            topology: replica_set
          - ruby: ruby-2.7
            gemfile: gemfiles/driver_min.gemfile
            mongodb: '4.2'
            topology: replica_set

          # BSON versions
          - ruby: ruby-3.2
            gemfile: gemfiles/bson_master.gemfile
            mongodb: '6.0'
            topology: replica_set
          - ruby: ruby-2.7
            gemfile: gemfiles/bson_min.gemfile
            mongodb: '4.2'
            topology: replica_set

          # JRuby
          - ruby: jruby-9.4
            gemfile: gemfiles/rails-7.0.gemfile
            mongodb: '6.0'
            topology: replica_set
          - ruby: jruby-9.4
            gemfile: gemfiles/rails-6.0.gemfile
            mongodb: '5.0'
            topology: server

    steps:
    - name: repo checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - id: start-mongodb
      name: start mongodb
      uses: mongodb-labs/drivers-evergreen-tools@master
      with:
        version: "${{matrix.mongodb || env.CI_DEFAULT_MONGODB}}"
        topology: "${{matrix.topology || env.CI_DEFAULT_TOPOLOGY}}"
    - name: load ruby
      uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMFILE: "${{matrix.gemfile || env.CI_DEFAULT_GEMFILE}}"
      with:
        ruby-version: "${{matrix.ruby}}"
        bundler: 2
    - name: bundle
      run: bundle install --jobs 4 --retry 3
      env:
        BUNDLE_GEMFILE: "${{matrix.gemfile || env.CI_DEFAULT_GEMFILE}}"
    - name: test
      timeout-minutes: 60
      continue-on-error: "${{matrix.experimental || false}}"
      run: bundle exec rake spec
      env:
        BUNDLE_GEMFILE: "${{matrix.gemfile || env.CI_DEFAULT_GEMFILE}}"
        MONGODB_URI: "${{steps.start-mongodb.outputs.cluster-uri}}"
